/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettlementRouteImport } from './routes/settlement'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContractsIndexRouteImport } from './routes/contracts.index'
import { Route as ContractsNewRouteImport } from './routes/contracts.new'

const SettlementRoute = SettlementRouteImport.update({
  id: '/settlement',
  path: '/settlement',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsIndexRoute = ContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsNewRoute = ContractsNewRouteImport.update({
  id: '/contracts/new',
  path: '/contracts/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settlement': typeof SettlementRoute
  '/contracts/new': typeof ContractsNewRoute
  '/contracts/': typeof ContractsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settlement': typeof SettlementRoute
  '/contracts/new': typeof ContractsNewRoute
  '/contracts': typeof ContractsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settlement': typeof SettlementRoute
  '/contracts/new': typeof ContractsNewRoute
  '/contracts/': typeof ContractsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settlement' | '/contracts/new' | '/contracts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settlement' | '/contracts/new' | '/contracts'
  id: '__root__' | '/' | '/settlement' | '/contracts/new' | '/contracts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettlementRoute: typeof SettlementRoute
  ContractsNewRoute: typeof ContractsNewRoute
  ContractsIndexRoute: typeof ContractsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settlement': {
      id: '/settlement'
      path: '/settlement'
      fullPath: '/settlement'
      preLoaderRoute: typeof SettlementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/': {
      id: '/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof ContractsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/new': {
      id: '/contracts/new'
      path: '/contracts/new'
      fullPath: '/contracts/new'
      preLoaderRoute: typeof ContractsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettlementRoute: SettlementRoute,
  ContractsNewRoute: ContractsNewRoute,
  ContractsIndexRoute: ContractsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
